knp_snappy:
    temporary_folder: "%kernel.cache_dir%/snappy"
    pdf:
        enabled: true
        binary: /usr/local/bin/wkhtmltopdf
        options: [ ]
    image:
        enabled: true
        binary: /usr/local/bin/wkhtmltoimage
        options: [ ]
